"""Agent domain types and schemas.

Defines input/output payloads, document chunks, tool interactions,
and failure injection configurations for the Enterprise Research Agent.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class FailureMode(str, Enum):
    """Supported deliberate engineering failure injection modes."""
    HEALTHY = "healthy"
    RETRIEVAL_MISS = "retrieval_miss"
    GENERATION_CONTRADICTION = "generation_contradiction"
    TOOL_RETRY_STORM = "tool_retry_storm"
    POLICY_BYPASS = "policy_bypass"
    CONTEXT_EXPLOSION = "context_explosion"
    EVALUATION_BLIND_SPOT = "evaluation_blind_spot"


class DocumentChunk(BaseModel):
    """A retrievable knowledge chunk from the enterprise corpus."""
    id: str
    title: str
    content: str
    category: str
    source: str
    score: float = 0.0
    metadata: Dict[str, Any] = Field(default_factory=dict)


class QueryClassification(BaseModel):
    """Classification of the user request."""
    category: str
    domain: str  # e.g. "financial", "technical", "hr", "general"
    sensitivity: str  # e.g. "public", "internal", "restricted"
    requires_tools: bool = False
    suggested_tools: List[str] = Field(default_factory=list)


class PlannedStep(BaseModel):
    """An individual step in the agent's reasoning plan."""
    step_id: int
    description: str
    tool_name: Optional[str] = None
    tool_arguments: Dict[str, Any] = Field(default_factory=dict)


class ExecutionPlan(BaseModel):
    """Decomposed plan produced by the planner stage."""
    reasoning: str
    steps: List[PlannedStep] = Field(default_factory=list)


class ToolExecutionResult(BaseModel):
    """Outcome of invoking an agent tool."""
    tool_name: str
    arguments: Dict[str, Any] = Field(default_factory=dict)
    arguments_hash: str = ""
    status: str = "success"  # "success", "error", "timeout"
    result: Any = None
    error_message: Optional[str] = None
    retry_count: int = 0
    latency_ms: float = 0.0


class PolicyCheckResult(BaseModel):
    """Result of policy verification guardrails."""
    decision: str  # "allow" or "deny"
    rules_evaluated: List[str] = Field(default_factory=list)
    violations: List[str] = Field(default_factory=list)
    is_bypassed: bool = False  # Set when policy_bypass failure is injected


class Citation(BaseModel):
    """Validation of source attribution in the generated answer."""
    claim: str
    document_id: str
    is_valid: bool = True
    reason: Optional[str] = None


class AgentRequest(BaseModel):
    """User request to the Enterprise Research Agent."""
    query: str
    request_id: Optional[str] = None
    session_id: Optional[str] = None
    tenant_id: str = "tenant_default"
    failure_mode: FailureMode = FailureMode.HEALTHY
    max_retries: int = 3
    parameters: Dict[str, Any] = Field(default_factory=dict)


class AgentResponse(BaseModel):
    """Final output generated by the Enterprise Research Agent."""
    request_id: str
    query: str
    answer: str
    classification: Optional[QueryClassification] = None
    retrieved_documents: List[DocumentChunk] = Field(default_factory=list)
    plan: Optional[ExecutionPlan] = None
    tool_results: List[ToolExecutionResult] = Field(default_factory=list)
    policy_check: Optional[PolicyCheckResult] = None
    citations: List[Citation] = Field(default_factory=list)
    duration_ms: float = 0.0
    status: str = "success"
    error: Optional[str] = None
